Makefile, include/BlockBuilder.hpp, include/Config.hpp, include/LocationBlock.hpp, include/LocationDirective.hpp, include/Parse.hpp, include/ServerBlock.hpp, include/ServerDirective.hpp, src/ADirective.cpp, src/BlockBuilder.cpp, src/Config.cpp, src/LocationBlock.cpp, src/LocationDirective.cpp, src/Parse.cpp, src/ServerBlock.cpp, src/main.cpp, www/a.conf
- BlockBuilder 클래스를 완성하고 에러메세지를 통일했습니다.
- BlockBuilder 클래스에 대한 이야기는 http_block, server_block, location_block 상속 문제  #12  를 참고 부탁드립니다.
- Config에서 HttpStr, ServerStr, LocationStr를 파싱하고 std::vector<std::pair<ServerBlock, std::vector >>>
- mServerBlockGroups을 만드는 과정을 BlockBuilder 클래스를 만들어서 config의 역할을 나눴습니다.
- BlockBuilder
- BlockBuilder.parseConfig(enum(Http, Server, Location)과 string)을 받아서 BlockBuilder의 내부 변수로 parse된 값을 들고 있습니다.
- BlockBuilder.buildHttpBlock()등을 만들어서 block클래스들을 반환합니다.
- 이렇게 파싱과 class을 만드는 과정을 쪼개서 위의 이슈를 해결했습니다.
- 부가적으로 동일한 로직의 파싱도 합쳤습니다.
- errorPage가 애매해서 일단 벡터로 pushback만 해놓은 상태입니다.
- cgi은 아직 이해가 안돼서 나중에 locationBlock의 매개변수 locationDirective의 init 함수의 수정이 필요합니다.
=> Feat/config BlockBuilder로 파싱및 block 생성

Makefile, include/BlockBuilder.hpp, include/Config.hpp, include/HttpBlock.hpp, include/LocationBlock.hpp, include/ServerBlock.hpp, include/ServerInfo.hpp, src/BlockBuilder.cpp, src/Config.cpp, src/HttpBlock.cpp, src/LocationBlock.cpp, src/ServerBlock.cpp, src/ServerInfo.cpp, www/a.conf
- ServerInfo클래스를 생성했습니다.
- BlockBuild 리셋 논리를 수정했습니다.
- **ServerInfo**
- ServerBlock, ServerBlock과 연관된 LocationBlock의 vector을 멤버변수로 가지고 있습니다
- 이에 맞게 Config 클래스를 수정했습니다.(생성자, 매개변수, createInstance)
- std::vector<std::pair<std::string, std::vector<std::string> > > mServerStr;를 std::vector\<ServerInfo>로 수정했습니다.
- **BlockBuild 리셋 논리 수정**
- 로직상 부모의 지시어가 있고 하위의 block에 동일한 지시어가 있을때 덮어쓰여지는것 까지는 잘됐습니다.
- nginx상 부모에 root a;가 있고 serverBlock에서 root가 있으면 있는 값으로 대체가 되고 없으면 부모의 값으로 반영이 되야 합니다.
- 하지만 이전의 로직으로는 부모의 값으로 반영이 되는게 아닌 앞서 나온 동등한 블록의 값으로 반영이 되는 문제를 확인했습니다.
- 이유는  이전 Config의 22번째줄에서 block을 만들기전 기본값으로만 reset을 해줍니다.
- 그래서 부모의 block의 getter을 만들고 부모개체를 받아서 부모의 값도 reset을 하게 수정해줬습니다.
- errorPage가 애매해서 일단 벡터로 pushback만 해놓은 상태입니다.
- cgi은 아직 이해가 안돼서 나중에 locationBlock의 매개변수 locationDirective의 init 함수의 수정이 …
=> feat: ServerInfo클래스 생성, block마다 getter 생성, BlockBuild 논리 수정

Makefile, include/Config.hpp, include/Parse.hpp, include/ServerInfoStr.hpp, src/Config.cpp, src/Parse.cpp, src/ServerInfoStr.cpp, src/main.cpp
#18 Parse 클래스에서 pair를 클래스로 리펙토링 했습니다.
- ServerInfoStr 클래스가 추가되었습니다.
- Parse의 getServerLocPairs 메소드가 getServerInfoStrs로 변경되었습니다.
- Config 클래스의 createInstance의 인자를 상수 참조자로 받는 것으로 리펙토링 했습니다.
=> [Refact] Parse 클래스 pair 자료형 ServerInfoStr 클래스로 리펙토링

Makefile, include/AEvent.hpp, include/Accept.hpp, include/BlockBuilder.hpp, include/Kqueue.hpp, include/Server.hpp, include/ServerManager.hpp, src/AEvent.cpp, src/Accept.cpp, src/BlockBuilder.cpp, src/Config.cpp, src/Kqueue.cpp, src/Server.cpp, src/ServerManager.cpp, src/main.cpp
- ServerInfo 벡터의 정보를 토대로 포트별로 Server 인스턴스 생성
- 동일 포트 동일 서버 이름이 있으면 예외처리
- 동일 포트의 서버 인스턴스가 존재하나 다른 서버 이름인 경우에는 서버 인스턴스의 ServerInfo 벡터에 push_back()
- enum blockType의 Server와 ServerManager 클래스의 멤버변수 std::vector<Server> mServers 가 
'Server' 라는 동일 키워드로 인해 컴파일 에러 발생
-> enum 값을 변경하여 해당 에러 해결
- 추상클래스인 AEvent의 생성자/소멸자 구현
- AEvent의 구현 클래스인 Accept 클래스 생성자/소멸자 및 가상함수 handle()의 오버라이딩 구현
=> [Feat] ServerManager와 Event 클래스 작성

include/event/AEvent.hpp, include/event/ReadFileEvent.hpp, include/event/ReadRequestEvent.hpp, include/parse/Config.hpp, include/server/Kqueue.hpp, src/event/ReadFileEvent.cpp, src/event/ReadRequestEvent.cpp, src/event/Request.cpp, src/event/WriteEvent.cpp, src/parse/Config.cpp, src/server/Kqueue.cpp, src/server/Server.cpp, src/server/ServerManager.cpp, www/a.conf
- Get 처리 여러 가지 사항들을 수정했습니다.
- 초기화가 미흡한 부분들을 추가했습니다.
- mRequestLine이 mStartLine으로 초기화를 안 해줘서 문제가 있었습니다.
- request 파싱이 끝나면 상태코드를 200으로 바꿔야 되는 이 부분이 안 되어 있어서 추가했습니다.
- read나 write가 실패하면 fd를 닫습니다. 
- 이 부분은 kevent error flag를 확인하는 게 있어서 미리 처리가 가능할 것도 같아요.
- fd를 닫기 때문에 소켓은 한번에 하나의 이벤트만 갖게 했습니다.
- 예를 들어 ReadRequest 이벤트가 끝나면 ReadFile 이벤트를 생성하고 ReadRequest 이벤트를 delete 합니다.
- delete를 이벤트 메소드로 안에 넣었습니다. 
- delete this
- 파일이 없으면 에러 페이지 보내주기
- kevent handle 메소드 리턴값 void로 바꾸기
=> [FIX] EVENT 수정

include/parse/BlockBuilder.hpp, include/parse/HttpBlock.hpp, include/parse/LocationBlock.hpp, include/parse/ServerBlock.hpp, src/main.cpp, src/parse/BlockBuilder.cpp, src/parse/HttpBlock.cpp, src/parse/LocationBlock.cpp, src/parse/ServerBlock.cpp
- #19
- BlockBuilder 클래스의 멤버변수 수정 및 추가(mErrorCodes, mErrorPages)
- BlockBuilder 클래스의 parseConfig() 에서 error_page 지시어 초기화 로직 수정
- BlockBuilder 클래스의 tryConvertNumber() 메소드명 및 로직 수정
- HttpBlock, ServerBlock, LocationBlock 클래스의 생성자 수정
- 기존의 mErrorPages 멤버변수를 Vector에서 Map으로 수정(ErrorCode - ErrorPagePath)
- mErrorCodes 멤버변수를 추가하여 상기 Map을 초기화하는 용도로 사용
- 기존의 convertNumber()를 mErrorPages를 초기화할 때도 재사용하기 위해 로직 수정
- mErrorPages의 컨테이너가 Vector에서 Map으로 수정됨에 따라 Block 클래스들의 생성자도 Vector에서 Map으로 변경
- error_page 지시어가 사용되지 않은 경우, 기본 내장 에러페이지를 보여주는 로직 추가
=> feat: Configuration 파일의 error_page 지시어 처리

include/event/ReadRequestEvent.hpp, include/event/Request.hpp, include/event/Response.hpp, include/parse/LocationBlock.hpp, include/server/HttpStatusInfos.hpp, include/server/Server.hpp, include/util.hpp, src/event/ReadFileEvent.cpp, src/event/ReadRequestEvent.cpp, src/event/Request.cpp, src/event/Response.cpp, src/parse/BlockBuilder.cpp, src/parse/LocationBlock.cpp, src/server/HttpStatusInfos.cpp, src/server/Server.cpp, src/util.cpp, www/a.conf, www/asdf/50x.html, www/asdf/index.html, www/autoIndex/hi/50x.html, www/new-year/index.html
- Server에 있는 getFilePath 로직을 readRequsetEvent로 옮겼습니다.
- Get 요청 시 파일이 없을 때 error 페이지를 응답합니다.
- Get 요청 시 폴더를 요청한 경우 경우에 따라 적절하게 응답합니다.
- Server에는 단순히 요청 경로에 부분일치하는 loctationBlock을 반환하는 getLocationBlockForRequest()을 추가했습니다.
- 이렇게 변경하게 된 이유는 getFilePath을 작성할 당시에는 부분일치하는 locationBlock의 인덱스 파일 벡터만 필요하다고 생각했습니다.
- 하지만 error_page, autoIndex등 더 필요한 부분이 있어서 맞는 locationBlock을 반환하게 변경했습니다.
- 파일이 없으면 conf 설정에 따라 에러 페이지를 보여줍니다. conf 파일이 없을 때는 하드코딩한 에러 html 문자열로 응답합니다
- 폴더 경로를 요청하는 경우 Index 지시어에 써있는 파일로 응답하거나 지시어가 없는 경우index.html를 찾습니다.
- 파일을 못찾을 경우 autoIndex 지시어에 따라 autoIndex 페이지를 반환하거나 에러 페이지를 반환합니다.
- mime type 헤더 적용
- 잘못된 요청일 경우 클라이언트 소켓 끊기(400, 501)
- Connection: close 일때 끊어주기
=> [FEAT] Get에서 에러페이지 및 오토인덱스 구현

include/event/ReadFileEvent.hpp, src/event/ReadFileEvent.cpp, src/event/ReadRequestEvent.cpp, src/event/Response.cpp
- response 헤더 추가하는 로직을 수정했습니다
- HTTP/1.1 200 200 처럼 상태코드, 사유가 아닌 상태 코드가 두 번 나오는 버그 수정했습니다.
- 이전의 로직은 status 200이 아닐때만  content-type이 response 헤더에 추가되는 문제가 있었습니다.
- 이유는 
-  src/event/ReadRequestEvent.cpp에서 236 ~ 243줄
``` C++
int fd = getRequestFd(status);
if (fd == -1)
{
makeResponseEvent(status);
}
else
{
makeReadFileEvent(fd, status);
}
```
- makeReadFileEvent
```C++
void ReadRequestEvent::makeReadFileEvent(int fd, int &status)
{
struct kevent newEvent;
// assert(mFileSize != 0);
EV_SET(&newEvent, mClientSocket, EVFILT_WRITE, EV_ADD, 0, 0,
new ReadFileEvent(mServer, mClientSocket, fd, mFileSize, status));
Kqueue::addEvent(newEvent);`
}
```
- 여기서 fd != -1이 아니면 makeReadFileEvent로 들어가는데 이 로직에서는 
- makeResponseEvent(status) 내부의 
``` C++
mResponse.addHead("Content-Type", mMimeType);
```
- 이 …
=> [fix]: response 헤더 추가하는 로직 수정

include/event/AEvent.hpp, include/event/ReadFileEvent.hpp, include/event/Response.hpp, include/event/WriteEvent.hpp, src/event/AEvent.cpp, src/event/ReadFileEvent.cpp, src/event/ReadRequestEvent.cpp, src/event/Response.cpp, src/event/WriteEvent.cpp
-  response 클래스를 활용하도록 Response, WriteEvent, ReadFileEvent 변경했습니다. #51 
-> mResponse.toStr() 구현했습니다.
-> mResponse.addBody(const std::string &body) 구현했습니다.
-> 생성자 WriteEvent(const Server &server, const Response &response, int clientSocket);로 변경했습니다.
-> 생성자 ReadFileEvent(const Server &server, const Response &response, int clientSocket, int fileFd, int fileSize);로 변경했습니다.
-> response을 ReadFileEvent 내부에서는 본문만 만들도록 수정(밖에서 시작줄, 헤더를 만든 response을 받음) 했습니다.
- 테스트 추가 필요 합니다.
- connectionType 구현 필요합니다.
=> refact: response 클래스를 활용하도록 Response, WriteEvent, ReadFileEvent 변경

include/parse/BlockBuilder.hpp, src/parse/BlockBuilder.cpp
- client_max_body_size 0 ~ 2147483647로 범위를 지정했습니다. #8 
- EUnit 값 수정했습니다.
- nginx상에는 max값이 정의 되어 있지 않지만 비슷한 서버인 아파치의 경우 2GB까지로 최댓값이 정의가 되어있습니다.
- 최댓값을 정의 하는것이 에러 탐색하기 용이할것 같아서 아파치의 경우를 참고했습니다.
- killo를 1000으로 정의 했었는데
- 실제 nginx에서는 1024로 되어있어서 수정했습니다.
- https://hg.nginx.org/nginx/file/default/src/core/ngx_parse.c
- 실제로 readRequestEvent에서 client_max_body_size가 잘 작동하는지 확인이 필요합니다
- [tryConvertNumber.cpp 설명](https://gist.github.com/guune/2002165d0eecfaf084ebe5b349c83774)
=> feat: client_max_body_size 0 ~ 2147483647로 범위를 지정

include/event/AEvent.hpp, include/event/ReadRequestEvent.hpp, include/event/Request.hpp, src/event/ReadRequestEvent.cpp, src/event/Request.cpp, src/server/HttpStatusInfos.cpp, www/a.conf
- Request 클래스에서 파일 업로드 크기 제한인 client_max_body_size와 limit_except deny POST와 같은 허용 메소드 지시어를 구하는 로직을 작성했습니다.
- AEvent의 멤버 변수인  Request 클래스를  ReadRequestEvent에서만 읽기 때문에 멤버 변수를 옮겼습니다.
- getLocationBlockForRequest 메소드를 이용해서 헤더를 파싱한 후 client_max_body_size와 허용 메소드를 알 수 있게 했습니다. 바디를 읽을 때 client_max_body_size 보다 더 많이 읽게되면 Bad Request를 응답합니다.
- 수정 사항이 몇가지 있습니다.
- 헤더 키값에 앞뒤 공백이 있을 때와 없을 때가 다른 헤더라고 판단해서 trim을 뺐습니다. (ngnix 테스트 중 "Host :"을 넣었을 때 Bad Request 응답)
- 501 에러페이지 HTML이 잘못되어 있어 수정했습니다.
- conf 파일에  get 요청이 limit 되어 있어 원활한 테스트를 위해 주석 처리했습니다. 
-
=> [FEAT] Request 클래스에서 파일 업로드  크기 제한과 허용 메소드 반영하는 로직 작성

include/event/Request.hpp, src/event/Request.cpp
- 요청 헤더: header parse에서  "Transfer-Encoding : chunked" 항목이 있을 시, chunked data를 병합하는 로직으로 들어갑니다. #60 
- Request class의 enum(eRequestLine)에 E_CHUNKED_CONTENTS가 추가되었습니다. 
- 그 다음 chunked 메세지를 순차적으로 받습니다.
- 메세지는 chunked size, chunked data 순으로 번갈아서 들어옵니다.
- 이 순서가 잘못되거나, 해당 내용이 없을 경우 에러로 mStatus를 설정하고 리턴합니다.
- chunked size는 16진수로 수신되고, 10진수로 변환 후 저장합니다.
- size가 유효하지 않은 범위이거나, buffer의 size 인덱스 직후에 CRLF가 아닐 시 에러를 리턴합니다.
- 정상적인 buffer로 확인되면 mBody에 해당 내용을 더해서 추가합니다. 
- 마지막 종료 메세지는 chunked size가 0, 읽을 buffer 내용이 없는 상태로 마무리 됩니다.정상종료 될 때 모든 내용 차곡차곡 mBody에 담겨져 있습니다.
- 기존의 header와 body를 parse 하는 로직을 차용했다가 위키에 내용에 CRLF 들어갈 수 있다는 제보를 반영해 내용에도 CRLF가 정상적으로 들어가도록 수정했습니다.
- chunked 는 POST 메소드로 만들었기 때문에 example.com으로 테스트하기가 어려웠습니다. 유사한 작동의 테스트가 필요합니다.
- CRLF가 내용에 있을 시, 줄바꿈된 상태로 들어가기 때문에 출력물이 조금 보기 어렵습니다. 역시 작동의 …
=> feat: chunked request 기능 추가

src/event/Request.cpp, src/server/HttpStatusInfos.cpp
- #8 
- #22
- #45 
- Configuration 파일의 "client_max_body_size" 지시어를 통해 본문의 크기가 지정된 경우 에러 추가되는 로직이 구현되었기에 이에 따른 413 에러코드 관련 정보를 추가
- HttpStatusInfos 클래스의 mHttpStatusReasons, mHttpErrorPages 각각의 맵에 에러 사유 및 에러 페이지 html 코드 추가
- Request 클래스의 parseRequestHeader(), parseChunkedContent() 에 mClientMaxBodySize를 비교하는 부분이 400 에러로 되어있어 413으로 수정
=> feat: 413 에러 코드 관련 value 및 로직 수정 

include/event/ReadRequestEvent.hpp, include/event/Response.hpp, src/event/ReadRequestEvent.cpp, src/event/Response.cpp, src/server/Server.cpp, www/a.conf
- ReadRequestEvent 로직을 수정했습니다.
- 이전 로직에서는 메세지 파싱에서 에러가 난 경우 error_page를 응답하기 위해 응답 처리 이전에 getErrorPageFd를 호출하고 응답 처리에서 에러가 발생했을 때도 getErrorPageFd를 호출해서 코드의 중복이 있었습니다.
- 로직을 변경해서 상태코드인 status 200일 경우에만 응답 처리를 하고, 200이 아닌 코드면 getErrorPageFd를 호출하게 변경했습니다. status가 200일 때에도 응답처리과정에서 에러가 발생할 수 있기 때문에 이후에도 상태코드가 변경되었는지 if 문을 보고 getErorrPageFd를 호출합니다. [참고](https://gist.github.com/heehoh/d66f0547d5dfeaeb4649ff43fed805fb)
- 요청에서 path가 비어있을 때에 config의 기본 서버로 응답해주기 위해 기본서버를 상속받는 location 블록을 리턴합니다. [참고](https://gist.github.com/heehoh/d5039c0b66c12c2d4f15150a4d6d1430)
- 로직이 변경됨에 따라 메소드명을 수정했습니다. init -> setStartLine 등등
-
=> [FEAT] ReadRequestEvent 클래스 로직 수정

include/event/Request.hpp, src/event/ReadRequestEvent.cpp, src/event/Request.cpp, src/server/HttpStatusInfos.cpp, www/a.conf
- location 블록에 return 지시어가 있을 때 해당 블록에 해당하는 요청이 올 때 요청을 리다이렉션 합니다.  #67 
- request 클래스에 mRedirectPath를 추가시켰고, return 지시어가 있을 때 지시어에 써있는 path를 받고 상태코드를 바꿉니다. 
- ReadRequestEvent에서 status가 307일 때 location 헤더를 추가해서 응답합니다.
=> [FEAT] 리다이렉션 구현

src/event/Request.cpp
- Request 클래스의 parseChunkedContent() 에서 받아온 데이터를 모두 처리하기 위해 반복문 및 탈출 조건을 추가
- Request 클래스의 checkChunkedData() 조건식을 한줄로 병합
- mStatus 수정
- parseChunkedContent()에서 받아온 버퍼를 모두 처리하지 않고 요청을 종료하는 문제점 발견, 반복문을 통해서 버퍼의 내용이 0이 될 때까지 모두 내용을 read하도록 반복문으로 로직을 변경.
- chunked size가 0으로 들어왔을 시, mBody의 내용도 0인, 쓰여진 내용이 없을 시 telnet 테스트에서는 400 에러를 리턴했으나, 테스터에서는 200으로 정상 종료로 처리되어 200으로 수정.
=> fix: Request Chunked Data 반복문 처리 및 탈출 조건 추가, 본문 없을 시 종료 코드 수정

include/event/Request.hpp, include/parse/BlockBuilder.hpp, include/server/HttpStatusInfos.hpp, src/event/ReadRequestEvent.cpp, src/event/Request.cpp, src/server/Server.cpp, www/a.conf
- 테스터 66초에 통과했습니다.
- 이전 코드에서는 chunked data를  0 CRLF CRLF를 만날 때까지 저장하고 이후 unchunked로 변환했는데 바로바로 저장해주는 로직으로 바꿨습니다. 그 결과 테스터가 7분 가량에서 66초로 줄었습니다.
- 멀티유저가 들어오는 테스터에서 요청을 수락하는 게 실패해서 listen의 인자를 5에서 1000으로 바꿨는데 더 유효한 값이 있는지 확인이 필요합니다.
-  
- CGI fork하는 로직 메소드로 따로 빼기
- 파일 업로드 CGI 만들기
- DELETE 구현
=> [FEAT] 테스터 통과

include/event/HttpEnum.hpp, include/event/ReadRequestEvent.hpp, src/event/ReadRequestEvent.cpp, src/server/HttpStatusInfos.cpp
- 상태코드 enum 추가했습니다.
- ReadRequsetEvent의 handle에 있던 cgi로직을 메소드로 옮겼습니다.
- addMimeTypeHeader()를 getFileExtension()메소드로 분리했습니다.
- ReadRequsetEvent 메소드에 매직넘버로 되어있던 상태코드를 enum를 추가하여 교체했습니다.
- makeCgiEvent() 메소드를 만들어서 분리했습니다.
- cgi 검사할때 cgi의 확장자와 locationBlock의 cgi_cgi_extension과 동일한지 비교하는 로직이 필요합니다
- cgi의 확장자의 로직이 addMimeTypeHeader내부의 fileExtension만 구하는 로직과 같아서 addMimeTypeHeader의 로직의 일부를 getFileExtension으로 만들었습니다.
- addMimeTypeHeader()은 getFileExtension()으로 확장자를 구한다음  mResponse.addHead("Content-type", HttpStatusInfos::getMimeType(getFileExtension(filePath))); 이런식으로 content-type를 필요한곳에 추가했습니다.
- mimeType를 더 추가해야 할 것 같습니다.
- kqueue 타이머 이벤트를 추가 해야 합니다.
=> [REFACT] 상태코드 enum 추가 및 ReadRequsetEvent의 handle에 있던 cgi로직을 메소드로 옮겼습니다.

include/event/ReadRequestEvent.hpp, include/event/Request.hpp, src/event/ReadRequestEvent.cpp, src/event/Request.cpp, src/server/HttpStatusInfos.cpp, src/server/Kqueue.cpp, src/server/Server.cpp
- 에러 수정 및 리펙토링 진행했습니다. 작업이 이곳 저곳으로 흩어져 있어요. 커밋을 하나씩 봐주세요.
- 8e59a7c55c4a1c0097bc6dd211a919696a8605f7 시작줄에 의도적으로 path를 넣지 않을 때 에러가 있어 200일 때만 getFileExtension을 호출하게 했습니다.
- fd5f593bdfdd5b17e580a66a97e34740d6be8adf lb를 두번 불러오는데 인자로 넘겨주고 한번만 불러오게 했습니다.
- d27353aebe0265deda98fbdf8e3d0f0f6765fd10 Request 메소드명이 불필요하게 긴 것 같아서 수정했습니다.
- c1a219f54cebbd2948ddd3937a69e8c171bbabe5 CGI 이벤트를 리펙토링 했습니다. 매직넘버를 enum으로 바꾸고, execve에 인자 넣는 방식을 좀 더 간략하게 바꿨습니다.
- 53f7645ab15cc22b430e8d9d7aff96b3b498c994 가독성을 위해 CGI를 요청하는지 확인하는 조건문을 메소드로 뺐습니다.
- 160ba7afdbf7979cafec3dd9237992d626be94f5 403 에러페이지 만들었습니다. #81 여기도 봐주세요.
- 12bc7653118b40983eeec601df65708ec0385d78 좀 더 명확하게 설명하려고 주석을 추가했습니다.
- b6810ef7fa673287afc44f49edaebbb9bff48e23 #79 에서 이야기 한대로 kqueue 매직넘버 상수화시켰습니다.
=> [FIX] 400, 403 응답일 때 에러 수정 및 가독성을 위한 리펙토링

include/event/ReadRequestEvent.hpp, src/event/ReadRequestEvent.cpp, src/server/HttpStatusInfos.cpp
- assert 오타 수정
- checkHeader를 checkReturnDirective로 수정
- #81 관련해서 assert 조건문이 올바르지 않아서 수정했습니다.
- checkHeader가 메소드명이 역할과 같지 않아서 checkReturnDirective로 수정했습니다.
-
=> [FIX] assert 오타 수정, checkHeader를 checkReturnDirective로 수정

include/event/ReadRequestEvent.hpp, src/event/ReadRequestEvent.cpp, src/event/Request.cpp
- ReadRequestEvent클래스의  checkCgi() 메소드 에서 cgiPath에 대한 예외 처리 로직 추가 했습니다. #83 
- chunked가 아니고 contentLength만큼 들어왔을때 mRequestLine = FINISH 추가 했습니다.
- access 함수를 통해서 존재하는지, 존재한다면 실행이 가능한지 체크를 합니다
- 없으면 404, 있어도 실행이 불가능하면 403에러를 띄우기 위해서 status의 레퍼런스를 매개변수로 받게 수정했습니다.
- 테스트 도중 chunkedData가 아니면 동작이 이상하게 되는 현상(content-length 만큼 넣어줘도 입력을 기다림)이 있었습니다.
- 디버그를 해보니 content-length만큼 들어왔을때  mRequestLine = FINISH 로직이 없어서 인것으로 알아냈습니다.
- mRequestLine = FINISH로직를 추가했습니다.
-
=> [FEAT] cgi path error check 추가 했습니다.

include/event/ReadCgiEvent.hpp, include/event/Response.hpp, include/util.hpp, src/event/ReadCgiEvent.cpp, src/event/Response.cpp, src/server/HttpStatusInfos.cpp, src/util.cpp
- cgi 반환값 처리해서 reponse 시작줄, 헤더에 추가하는 로직을 추가했습니다.
- 500에러 추가 및 setStartLine 오버로딩 추가했습니다.
- caseInsensitiveMatch() 대소문자 구분없이 비교하는 메소드 추가했습니다.
- 원래 로직은 cgi 반환값이 어떤 값이든 reponse의 시작줄을 200 ok로 해서 클라이언트 소켓에 보냈습니다.
- 그 로직을 수정해서 \r\n\r\n이 나올때 까지 cgi의 반환값을 해석해서 reponse의 시작줄 및 헤더에 넣어줬습니다.
- 만약 cgi의 반환값으로 status를 넣어주지 않았다면 오류로 판단을 했고 500에러를 반환하게 했습니다.
- status: 200 ok 이런식으로 cgi가 반환하기 때문에 string을 받아서 startLine를 만드는 생성자오버로딩을 추가 했습니다.
- status, Status 구분 없이 받기 위해 util에 caseInsensitiveMatch()를 추가했습니다.
- 파일업로드 cgi랑 잘 맞는지 확인이 필요합니다.
=> [FEAT] cgi 반환값 처리해서 reponse 시작줄, 헤더에 추가하는 로직을 추가했습니다.

include/event/ReadRequestEvent.hpp, include/event/Request.hpp, include/parse/BlockBuilder.hpp, include/parse/LocationBlock.hpp, src/event/ReadRequestEvent.cpp, src/event/Request.cpp, src/parse/BlockBuilder.cpp, src/parse/LocationBlock.cpp, src/parse/LocationDirective.cpp, www/a.conf
- conf 파일 지시어로 cgi_upload_dir 추가했습니다.
- checkCgiEvent()에서 cgi 확장자 검색하는 로직 및 setPathInfo 하는 로직 추가 했습니다.
- Request클래스에 pathInfo 멤버변수 추가 및 getCgiEnvp() 메소드 내부 환경변수 덧붙이는 로직 추가 했습니다.
- 환경변수 추가 내용은 #93 를 참고바랍니다                                                                                                                                                                                                                                                                                                                                                                                                                        
- cgi fileUpload 및 delete 구현 하는 도중 upload_dir의 위치를 지정하면 좋겠다라는 의견이 있었습니다.
- 그 의견에 맞게 conf 파일 지시어로 cgi_upload_dir를 추가했습니다.
- 기본값은 "/" 입니다
- pathInfo를 환경변수로 받음으로써 cgi의 경우 확장자 처리 하는 로직을 변경할 …
=> [Feat] cgi 환경변수를 덧붙이는 로직을 추가했습니다.

src/event/ReadRequestEvent.cpp
- #99 
- autoIndex 관련 에러가 있어서 수정했습니다.
- 폴더를 요청한 경우 과거의 로직은 index 파일들이 있는지 확인 없으면 autoIndex가 켜져 있는지 확인를 했습니다.
- 이 과정에서 없는 폴더가 들어온 경우도 autoIndex가 locationBlock에 on 되어 있으면 autoIndex 홈페이지가 켜지는 에러가 있었습니다.
- 그래서 맨 앞에 폴더가 존재하는지 여부를 체크하는 로직을 추가했습니다.
-
=> [FIX] 요청한게 folder일때 folder가 존재하는지 에러 탐색 로직 추가

src/server/HttpStatusInfos.cpp
- mimeType의 기본값이 ""으로 되는 에러가 있어서 수정했습니다.
- .html이여야 하는데 html이여서 ""으로 되어서 수정했습니다.
- 기본값이 text/html 이였는데 text/plain으로 수정했습니다.
-
=> [FIX] get mime type에러 수정

src/event/Request.cpp, src/server/HttpStatusInfos.cpp
- X-header 범용적으로 처리했습니다.
- 원래 로직은 X-Secret-Header-For-Test에 맞는 경우만 HTTP_를 앞에 붙여줬습니다.
- 맨앞에 X-가 있는경우에 HTTP_를 붙이는것으로 수정했습니다.
-
=> [Fix] X-header 범용적으로 처리했습니다.

cgi-bin/upload.py, www/new-year/index.html
- 페이지 이동 없이 파일 업로드 가능하게 했습니다.
- 기존 form 태그만으로 POST 요청을 보낼 때 브라우저를 새로고침 했을 때 다시 POST 요청을 보내는 문제가 있었습니다. 
- 그래서  DELETE 요청과 마찬가지로 자바스크립트 코드를 추가해서 자바 스크립트에서 POST 요청을 보내고 응답이 오면 페이지를 리로드(GET 요청)해서 POST가 반영된 페이지를 보여줍니다.
- 요청이 자바스크립트 내에서 처리가 됨으로 브라우저에서 새로고침을 했을 때 POST 요청을 다시 보내는 것이 아니라 GET 요청을 보내 POST를 중복해서 보내는 것을 방지했습니다.
`크롬에서 post 요청을 다시 보낼 때 나오는 경고창`
- 파이썬 코드는 CGI 프로세스에서 실행되고 자바스크립트 코드는 웹브라우저에서 실행됩니다.
- [파이썬 코드](https://gist.github.com/heehoh/6ac1608af30bbbfe1f2f0b407b7f1f11)
- [자바스크립트 간략 설명](https://gist.github.com/heehoh/37471c151e16a39fbf2ddec3b663f6f3)
=> [FEAT] 페이지 이동 없이 파일 업로드 가능

Makefile, include/event/AEvent.hpp, include/event/ReadCgiEvent.hpp, include/event/ReadFileEvent.hpp, include/event/ReadRequestEvent.hpp, include/event/WriteCgiEvent.hpp, include/server/Kqueue.hpp, src/event/AEvent.cpp, src/event/AcceptEvent.cpp, src/event/ReadCgiEvent.cpp, src/event/ReadFileEvent.cpp, src/event/ReadRequestEvent.cpp, src/event/WriteCgiEvent.cpp, src/event/WriteEvent.cpp, src/server/HttpStatusInfos.cpp, src/server/Kqueue.cpp
- timer 이벤트 추가했습니다. #92 
- 타이머랑 동일한 fd를 가진 다른 이벤트(ReadRequestEvent, writeEvent, readFileEvent등)가 kevent에서 반환되면 타이머 이벤트는 continue로 넘기고 다른 이벤트를 실행하는 메소드 입니다.
- 클라이언트에서 연결된 후 클라이언트에서 request요청(get 등)이 일정시간동안 없을때 발생합니다.
- timer를 삭제하고 mClientSocket를 close 해줍니다.
- readFileEvent에서 일정시간동안 file을 read를 못하면 발생합니다.
- timer를 삭제하고 408 관련된 response를 생성하고 writeEvent를 생성합니다.
- cgi에게 write가 일정시간동안 못하면 발생합니다.
- timer를 삭제하고 관련된 파일을 close 합니다.
- cgi에게 read를 일정시간동안 못하면 발생합니다.
- timer를 삭제하고 500 관련된 response를 생성하고 writeEvent를 생성합니다.
- ### TODO
- ReadFileEvent->timer()에서 타이머가 발생하면 408이 맞는지 검토가 필요합니다.
- ReadRequestEvent->timer()에 에러처리가 올바른지 검토가 필요합니다.
- 지금은 test에 맞게 10초로 설정을 했는데 일정시간에 대한 고민이 필요합니다
=> [FEAT] timer 이벤트 추가했습니다.

src/parse/BlockBuilder.cpp, src/parse/ServerBlock.cpp, src/server/Server.cpp
-  부분일치 문제 로직 수정했습니다.
-  Server::getLocationBlockForRequest()의     
``` C++
for (; locIt != targetServerInfo.getLocationBlocks().end(); ++locIt)
{
if (path.find(locIt->getLocationPath()) == 0)
{
return *locIt;
}
}
```
- 의 로직에 문제가 있어서 수정했습니다
- 예를 들어서 path가 /directory123.html이고 locIt->getLocationPath()가 /directory, /abc, / 일때
- /directory가 반환되는 문제가 있었습니다.
- 부분일치로직을 포함해서 에러 체크하는 로직을 추가 했습니다.
- 자세한 내용은 gist를 참고바랍니다.
-
- https://gist.github.com/guune/baadbeb782473f22b2b7a51080db88fc
=> [FIX] 부분일치 문제 로직 수정했습니다.

cgi-bin/upload.pl
- 이모지 유니코드 마다 길이가 달라 maxLength 속성을 지웠습니다.
=> [HOTFIX] 이모지 글자 길이 문제

src/main.cpp
- 좀비 프로세스 처리를 SIG_IGN로 처리합니다.
- SIG_IGN로 처리하는 이유는 자식프로세스의 종료상태를 확인하지 않기 때문에 wait을 쓰지 않기로 했습니다.
-
=> [FEAT] 좀비프로세스 처리

src/event/ReadRequestEvent.cpp, src/parse/BlockBuilder.cpp, src/parse/LocationBlock.cpp
- mIsAllowedDelete의 기본값을 false로 변경했습니다.
- filesize가 0일때 로직 수정했습니다.
- 모든곳에서 delete를 허용하는게 보안상 좋지 않을것 같아서 기본값을 false로 바꿨습니다.
- 0일때 읽으려고 시도하면 block이 되서 close를 해주고 body가 없이 writeEvent를 호출합니다.
-
=> [FIX] mIsAllowedDelete의 기본값을 false로 변경했습니다. filesize가 0일때 로직 수정했습니다.

src/server/HttpStatusInfos.cpp, www/a.conf
- a.conf 수정 및 mime-type에 charset=UTF-8 추가했습니다.
- a.conf에 DELETE allow된 부분이 추가되었습니다.
- charset=UTF-8을 text/html mimetype에 추가 시켰습니다.
=> [REFACT] a.conf 수정 및 mime-type에 charset=UTF-8 추가
